final info script

diff --git a/files/info b/files/info
--- a/files/info
+++ b/files/info
@@ -2,23 +2,6 @@
 
 # info - a CLI Bash script to show system/theme info in screenshots
 
-# Adapted on the work from Copyright (c) 2010-2019 Brett Bohnenkamper <kittykatt@kittykatt.us>
-# Copyright (c) 2020 Bob Liotta <bob@262.life>
-
-#  This program is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation, either version 3 of the License, or
-#  (at your option) any later version.
-#
-#  This program is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
-#
-#  You should have received a copy of the GNU General Public License
-#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-
 scriptVersion="3.9.1"
 
 ######################
@@ -98,20 +81,6 @@ customlines () {
 	# Also make sure the $custom0 variable in out_array=... matches the one at the beginning of the line
 	#
 	custom0=$(echo -e "$labelcolor YOUR LABEL:$textcolor your text"); out_array=( "${out_array[@]}" "$custom0" ); ((display_index++));
-
-	# Battery percentage and time to full/empty:
-	# (uncomment lines below to use)
-	#
-	#custom1=$(echo -e "$labelcolor Battery:$textcolor $(upower -d | grep percentage | head -n1 | cut -d ' ' -f 15-)"); out_array=( "${out_array[@]}" "$custom1" ); ((display_index++));
-	#if [ "$(upower -d | grep time)" ]; then
-	#	battery_time="$(upower -d | grep time | head -n1 | cut -d ' ' -f 14-) $(upower -d | grep time | head -n1 | cut -d ' ' -f 6-7 | cut -d ':' -f1)"
-	#else
-	#	battery_time="power supply plugged in"
-	#fi
-	#custom2=$(echo -e "$labelcolor $(echo '  `->')$textcolor $battery_time"); out_array=( "${out_array[@]}" "$custom2" ); ((display_index++));
-
-	# Display public IP:
-	#custom3=$(echo -e "$labelcolor Public IP:$textcolor $(curl -s ipinfo.io/ip)"); out_array=( "${out_array[@]}" "$custom3" ); ((display_index++));
 
 	###########################################
 	##	MY CUSTOM LINES
@@ -349,8 +318,8 @@ while getopts ":hsu:evVEnLNtlS:A:D:o:c:d:pa:w" flags; do
 	case $flags in
 		h) displayHelp; exit 0 ;;
 		s) screenshot='1' ;;
-		S) screenCommand="${OPTARG}" ;;
-		u) upload='1'; uploadLoc="${OPTARG}" ;;
+#		S) screenCommand="${OPTARG}" ;;
+#		u) upload='1'; uploadLoc="${OPTARG}" ;;
 		v) verbosity=1 ;;
 		V) displayVersion; exit 0 ;;
 		E) errorSuppress='1' ;;
@@ -358,7 +327,7 @@ while getopts ":hsu:evVEnLNtlS:A:D:o:c:d:pa:w" flags; do
 		A) asc_distro="${OPTARG}" ;;
 		t) truncateSet='Yes' ;;
 		n) display_type='Text' ;;
-		L) display_type='ASCII'; display_logo='Yes' ;;
+		L) display_type='ASCII';; #display_logo='Yes' ;;
 		o) overrideOpts="${OPTARG}" ;;
 		c) detectColors "${OPTARGS}" ;;
 		d) overrideDisplay="${OPTARG}" ;;
@@ -933,28 +902,47 @@ asciiText () {
 			fi
 			if [ -n "${my_lcolor}" ]; then c1="${my_lcolor}"; c2="${my_lcolor}"; fi
 			startline="0"
-			logowidth="36"
-			fulloutput=(
 
-"${c4}             ${b}              %s"
-"${c4}           ${b}${b}${b}${b}${b}            %s"
-"${c4}        /${b}${b}${b}${b}${b}${b}${b}${b}${b}\         %s"
-"${c4}      /${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}\       %s"
-"   ${c4}/${b}${b}${b}${b}${c1}${b}${b} ${b}${b}${b}${b}${b}${c4}${b}${b}${b}${b}${b}${b}${b}\    %s"
-"   ${c4}${b}${b}${b}${b}${b}${c1}${b}${b} ${b}${b}${b}${b}${b}${b}${c4}${b}${b}${b}${b}${b}${b}${b}    %s"
-"  ${c4}/${b}${b}${b}${b}${b}${c1}${b}${b} ${b}${b}${b}${b}${b}${b}${c4}${b}${b}${b}${b}${b}${b}${b}\   %s"
-"  ${c4}${b}${b}${b}${b}${b}${b}${c1}${b}${b} ${b}${b}${b}${b}${b}${c4}${b}${b}${b}${b}${b}${b}${b}${b}${b}   %s"
-"  ${c4}${b}${b}${b}${b}${b}${b}${c1}${b}${b}      ${b}${b}${c4}${b}${b}${b}${b}${b}${b}${b}   %s"
-" ${c4}${b}${b}${b}${b}${b}${b}${b}${c1}${b}${b} ${b}${b}${b}${b}${b} ${b}${b}${c4}${b}${b}${b}${b}${b}${b}${b}  %s"
-"  ${c4}${b}${b}${b}${b}${b}${b}${c1}${b}${b}${b}${b}${b}${b}${b}${b}${b} ${b}${b}${c4}${b}${b}${b}${b}${b}   %s"
-"  ${c4} ${b}${b}${b}${b}${b}${c1}${b}${b}      ${b}${b} ${b}${b}${c4}${b}${b}${b}    %s"
-"  ${c4}  ${b}${b}${b}${b}${c1}${b}${b}      ${b}${b} ${b}${b}${c4}${b}${b}     %s"
-"  ${c4}   ${b}${b}${b}${c1}${b}${b}${b}${b}${b}${b}${b}${b}${b} ${b}${b}${c4}${b}${b}      %s"
-"  ${c4}    ${b}${b}${c1}${b}${b} ${b}${b}${b}${b}${b} ${b}${c4}${b}${b}${b}       %s"
-"  ${c4}     ${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}  ${c1}       B A S H   o n   B o a r d !          %s"
-"  ${c4}      ${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}   "
-"${c2}                                        %s"
-"${c4}  ${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}${b}")
+declare -a RAINBOW
+if is_tty; then
+  RAINBOW=(
+    "$(printf '\033[38;5;196m')"
+    "$(printf '\033[38;5;202m')"
+    "$(printf '\033[38;5;226m')"
+    "$(printf '\033[38;5;082m')"
+    "$(printf '\033[38;5;021m')"
+    "$(printf '\033[38;5;093m')"
+    "$(printf '\033[38;5;163m')"
+  )
+
+  RED=$(printf '\033[31m')
+  GREEN=$(printf '\033[32m')
+  YELLOW=$(printf '\033[33m')
+  BLUE=$(printf '\033[34m')
+  BOLD=$(printf '\033[1m')
+  RESET=$(printf '\033[0m')
+fi
+
+#echo "test" "${out_array[@]}"
+
+###LOGO
+printf  "${BLUE}${BOLD}%s %s${RESET}\n"
+# printf "${BLUE}%s \`${BOLD}%s${RESET}${BLUE}\`${RESET}\n" "You can see the changelog with" "omz changelog"
+printf "\n"
+printf  '%s    ____ %s %s         %s  __%s %s%s                %s|\n'  ${RAINBOW[*]} $RESET 
+printf  '%s   / __ )%s____ %s _____%s/ /_  %s____  %s____%s    %s|%s%s\n'  ${RAINBOW[*]} $RESET "${out_array[1]}" "${out_array[2]}"
+printf  '%s  / __  /%s __ `%s/ ___/%s __ \%s/ __ \%s/ __ \%s   %s|%s\n'  ${RAINBOW[*]} $RESET "${out_array[4]}"
+printf  '%s / /_/ /%s /_/ %s(__  )%s / / /%s /_/ /%s / / /%s   %s|%s%s\n'  ${RAINBOW[*]} $RESET "${out_array[8]}" "${out_array[5]}"
+printf  '%s/_____/%s\__,_%s/____/%s_/ /_/%s\____/%s_/ /_/%s    %s|%s\n'  ${RAINBOW[*]} $RESET "${out_array[6]}"
+printf  '%s    ____   %s%s%s                    %s__%s   __%s  %s|%s\n'  ${RAINBOW[*]} $RESET "${out_array[7]}"
+printf  '%s   / __ )%s____  %s____%s  _____%s____/ /%s  / /%s  %s|%s\n'  ${RAINBOW[*]} $RESET "${out_array[13]}"
+printf  '%s  / __  /%s __ \%s/ __ `%s/ ___/%s __  /%s  / /%s   %s|%s%s%s\n'  ${RAINBOW[*]} $RESET "${out_array[11]}" "${out_array[9]}" "${out_array[10]}"
+printf  '%s / /_/ /%s /_/ %s/ /_/ /%s /  %s/ /_/ / %s /_/%s    %s|\n'  ${RAINBOW[*]} $RESET 
+printf  '%s/_____/%s\____/%s\__,_/%s_/   %s\__,_/  %s%s%s(_)     |%s%s\n'  ${RAINBOW[*]} $RESET "${YELLOW}${BOLD} B A S H   o n   B o a r d !"
+printf  "\n"
+
+printf  "${BLUE}${BOLD}%s %s${RESET}\n" "To keep up with the latest news and updates, follow us on Twitter:" "$(fmt_link @262life_bob https://twitter.com/262life_bob)"
+#printf  "${BLUE}${BOLD}%s %s${RESET}\n" "Want to get involved in the community? Join our Discord:" "$(fmt_link "Discord server" https://discord.gg/ohmyzsh)"
 
 
 
@@ -969,8 +957,10 @@ asciiText () {
 			fulloutput+=("${c1}$(printf '%s' "$logowidth")")
 		done
 		for ((i=0; i<${#fulloutput[@]}; i++)); do
-			my_out=$(printf "${fulloutput[i]}$c0\n" "${out_array}")
-			my_out_full=$(echo "$my_out" | cat -v)
+      ###BOB
+			#my_out=$(printf "${fulloutput[i]}$c0\n" "${out_array}")
+			#my_out=$(printf  "${out_array}")
+#			my_out_full=$(echo "$my_out" | cat -v)
 			termWidth=$(tput cols)
 			#SHOPT_EXTGLOB_STATE=$(shopt -p extglob)
 			#read SHOPT_CMD SHOPT_STATE SHOPT_OPT <<< "${SHOPT_EXTGLOB_STATE}"
@@ -1018,24 +1008,6 @@ asciiText () {
 				out_array=( "${out_array[@]}" )
 			fi
 		done
-	elif [[ "$portraitSet" = "Yes" ]]; then
-		for i in "${!fulloutput[@]}"; do
-			printf "${fulloutput[$i]}$c0\n"
-		done
-
-		printf "\n"
-
-		for ((i=0; i<${#fulloutput[*]}; i++)); do
-			[[ -z "${out_array[0]}" ]] && continue
-			printf "%s\n" "${out_array[0]}"
-			unset 'out_array[0]'
-			out_array=( "${out_array[@]}" )
-		done
-
-	elif [[ "$display_logo" == "Yes" ]]; then
-		for i in "${!fulloutput[@]}"; do
-			printf "${fulloutput[i]}$c0\n"
-		done
 	else
 		if [[ "$lineWrap" = "Yes" ]]; then
 			availablespace=$(($(tput cols) - logowidth + 16)) #I dont know why 16 but it works
@@ -1052,10 +1024,6 @@ asciiText () {
 			out_array=("${new_out_array[@]}")
 		fi
 		missinglines=$((${#out_array[*]} + startline - ${#fulloutput[*]}))
-		for ((i=0; i<missinglines; i++)); do
-			fulloutput+=("${c1}$(printf '%s' "$logowidth")")
-		done
-		#n=${#fulloutput[*]}
 		for ((i=0; i<${#fulloutput[*]}; i++)); do
 			# echo "${out_array[@]}"
 			case $(awk 'BEGIN{srand();print int(rand()*(1000-1))+1 }') in
@@ -1075,7 +1043,7 @@ asciiText () {
 					done
 				;;
 			esac
-			printf "${fulloutput[i]}$c0\n" "${out_array[0]}"
+			#printf "${fulloutput[i]}$c0\n" "${out_array[0]}"
 			if [[ "$i" -ge "$startline" ]]; then
 				unset 'out_array[0]'
 				out_array=( "${out_array[@]}" )
@@ -1164,6 +1132,7 @@ infoDisplay () {
 		for (( i = 0; i < ${#display[@]}; i++ ))
         do
           display_list="$display_list ${display[$i]}"
+
         done
 		if [[ "${display_list}" =~ "host" ]]; then
 			myinfo=$(echo -e "${labelcolor} ${myUser}$textcolor${bold}@${c0}${labelcolor}${myHost}")
@@ -1401,6 +1370,77 @@ infoDisplay () {
 	fi
 }
 
+# The [ -t 1 ] check only works when the function is not called from
+# a subshell (like in `$(...)` or `(...)`, so this hack redefines the
+# function at the top level to always return false when stdout is not
+# a tty.
+if [ -t 1 ]; then
+  is_tty() {
+   true
+  }
+else
+  is_tty() {
+     false
+  }
+fi
+ 
+supports_hyperlinks() {
+  # $FORCE_HYPERLINK must be set and be non-zero (this acts as a logic bypass)
+  if [ -n "$FORCE_HYPERLINK" ]; then
+    [ "$FORCE_HYPERLINK" != 0 ]
+    return $?
+  fi
+ 
+  # If stdout is not a tty, it doesn't support hyperlinks
+  is_tty || return 1
+ 
+  # DomTerm terminal emulator (domterm.org)
+  if [ -n "$DOMTERM" ]; then
+    return 0
+  fi
+ 
+  # VTE-based terminals above v0.50 (Gnome Terminal, Guake, ROXTerm, etc)
+  if [ -n "$VTE_VERSION" ]; then
+    [ $VTE_VERSION -ge 5000 ]
+    return $?
+  fi
+ 
+  # If $TERM_PROGRAM is set, these terminals support hyperlinks
+  case "$TERM_PROGRAM" in
+  Hyper|iTerm.app|terminology|WezTerm) return 0 ;;
+  esac
+ 
+  # kitty supports hyperlinks
+  if [ "$TERM" = xterm-kitty ]; then
+    return 0
+  fi
+ 
+  # Windows Terminal or Konsole also support hyperlinks
+  if [ -n "$WT_SESSION" ] || [ -n "$KONSOLE_VERSION" ]; then
+    return 0
+  fi
+
+  return 1
+}
+ 
+ fmt_link() {
+   # $1: text, $2: url, $3: fallback mode
+   if supports_hyperlinks; then
+     printf '\033]8;;%s\a%s\033]8;;\a\n' "$2" "$1"
+     return
+   fi
+ 
+   case "$3" in
+   --text) printf '%s\n' "$1" ;;
+   --url|*) fmt_underline "$2" ;;
+   esac
+ }
+
+fmt_underline() {
+  is_tty && printf '\033[4m%s\033[24m\n' "$*" || printf '%s\n' "$*"
+}
+
+
 ##################
 # Let's Do This!
 ##################
@@ -1492,4 +1532,3 @@ fi
 infoDisplay
 
 exit 0
-
